###################
### Extensions ####
###################
FROM ghcr.io/keitaroinc/ckan:2.9.5 as extbuild

# Locations and tags, please use specific tags or revisions
ENV HIERARCHY_GIT_URL=https://github.com/ckan/ckanext-hierarchy
ENV HIERARCHY_GIT_BRANCH=master

# Switch to the root user
USER root

# Fetch and build the custom CKAN extensions
RUN pip wheel --wheel-dir=/wheels git+${HIERARCHY_GIT_URL}@${HIERARCHY_GIT_BRANCH}#egg=ckanext-hierarchy
RUN pip wheel --wheel-dir=/wheels -r https://raw.githubusercontent.com/ckan/ckanext-hierarchy/${HIERARCHY_GIT_BRANCH}/requirements.txt
RUN curl -o /wheels/hierarchy.txt https://raw.githubusercontent.com/ckan/ckanext-hierarchy/${HIERARCHY_GIT_BRANCH}/requirements.txt

USER ckan

############
### MAIN ###
############
FROM ghcr.io/keitaroinc/ckan:2.9.5

LABEL maintainer="Keitaro Inc <info@keitaro.com>"

#ENV CKAN__PLUGINS envvars s3filestore image_view webpage_view text_view recline_view datastore datapusher hierarchy
ENV CKAN__PLUGINS envvars  image_view webpage_view text_view recline_view datastore datapusher hierarchy_display hierarchy_form
# Switch to the root user
USER root

COPY --from=extbuild /wheels /srv/app/ext_wheels
#RUN cd /usr/lib/ckan/default/src 
# Install and enable the custom extensions
RUN pip install -e "git+https://github.com/davidread/ckanext-hierarchy.git#egg=ckanext-hierarchy" && \
    pip install -r ckanext-hierarchy/requirements.txt && \
    ckan config-tool "${APP_DIR}/production.ini" "ckan.plugins = ${CKAN__PLUGINS}" && \
    chown -R ckan:ckan /srv/app
#RUN pip install --no-index --find-links=/srv/app/ext_wheels ckanext-s3filestore && \
 #   pip install --no-index --find-links=/srv/app/ext_wheels -r /srv/app/ext_wheels/s3filestore.txt && \
  #  ckan config-tool "${APP_DIR}/production.ini" "ckan.plugins = ${CKAN__PLUGINS}" && \
   # chown -R ckan:ckan /srv/app

# Remove wheels
RUN rm -rf /srv/app/ext_wheels

USER ckan
